CC=g++
FLAGS=-Wall -g
LIBS =
RULE=MEM50
RM=rm
BUILD_L = ./build.log
OUTPUT = ./output.log

all:
	$(CC) $(FLAGS) ./src/*.cpp -o rule_$(RULE) $(LIBS) 2>> $(BUILD_L)

clean:
	$(RM) rule_$(RULE) $(BUILD_L)
